return {
    version = 1,
    name = "map001",
    tiles = {
        { layer = "base", q = -6, r = 2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -6, r = 3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -6, r = 4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -6, r = 5, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -6, r = 6, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -6, r = 7, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -6, r = 8, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 0, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 5, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 6, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 7, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -5, r = 8, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -4, r = -1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -4, r = 0, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -4, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -4, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -4, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -4, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -4, r = 5, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -4, r = 6, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -4, r = 7, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -4, r = 8, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -3, r = -2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -3, r = -1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -3, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 5, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 6, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -3, r = 7, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -2, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -2, r = -2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -2, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 5, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 6, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -2, r = 7, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -1, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = -1, r = -2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 5, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 6, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 0, r = -4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 0, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 0, r = -2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 5, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 0, r = 6, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 1, r = -4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 1, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 1, r = -2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 1, r = 5, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 2, r = -4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 2, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 2, r = -2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 2, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 2, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 2, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 2, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 2, r = 3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 2, r = 4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 2, r = 5, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = -4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = -2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = -1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = 0, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = 1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = 2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = 3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 3, r = 4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = -4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = -2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = -1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = 0, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = 1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = 2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = 3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 4, r = 4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = -4, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = -3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = -2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = -1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = 0, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = 1, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = 2, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "base", q = 5, r = 3, folder = "green", name = "PH2_FjordSummerGrass_4.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_4.png" },
        { layer = "river", q = -4, r = 1, folder = "rivers", name = "PH2_RiverNordic_22.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_22.png" },
        { layer = "river", q = -3, r = 1, folder = "rivers", name = "PH2_RiverNordic_22.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_22.png" },
        { layer = "river", q = -2, r = 1, folder = "rivers", name = "PH2_RiverNordic_01.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_01.png" },
        { layer = "river", q = -2, r = 2, folder = "rivers", name = "PH2_RiverNordic_35.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_35.png" },
        { layer = "river", q = -1, r = 2, folder = "rivers", name = "PH2_RiverNordic_32.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_32.png" },
        { layer = "river", q = 0, r = 1, folder = "rivers", name = "PH2_RiverNordic_10.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_10.png" },
        { layer = "river", q = 1, r = 1, folder = "rivers", name = "PH2_RiverNordic_23.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_23.png" },
        { layer = "river", q = 2, r = 1, folder = "rivers", name = "PH2_RiverNordic_00.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_00.png" },
        { layer = "river", q = 2, r = 2, folder = "rivers", name = "PH2_RiverNordic_12.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_12.png" },
        { layer = "overlay", q = -4, r = 1, folder = "woods", name = "PH2_ThickForest_22.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_22.png" },
        { layer = "overlay", q = -4, r = 2, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -4, r = 3, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -4, r = 4, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -4, r = 5, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -3, r = 0, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -3, r = 2, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -3, r = 3, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -2, r = -1, folder = "woods", name = "PH2_ThickForest_04.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_04.png" },
        { layer = "overlay", q = -1, r = -2, folder = "woods", name = "PH2_ThickForest_04.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_04.png" },
        { layer = "overlay", q = -1, r = -1, folder = "woods", name = "PH2_ThickForest_04.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_04.png" },
        { layer = "overlay", q = -1, r = 4, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -1, r = 5, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = 0, r = -2, folder = "woods", name = "PH2_ThickForest_04.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_04.png" },
        { layer = "overlay", q = 0, r = 3, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = 1, r = -2, folder = "woods", name = "PH2_ThickForest_04.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_04.png" },
        { layer = "overlay", q = 1, r = 0, folder = "woods", name = "PH2_ThickForest_46.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_46.png" },
        { layer = "overlay", q = 2, r = -1, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = 2, r = 0, folder = "woods", name = "PH2_ThickForest_46.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_46.png" },
    },
    markers = {
        { type = "terrain", q = -4, r = 1, value = "jng" },
        { type = "terrain", q = -4, r = 2, value = "jng" },
        { type = "terrain", q = -4, r = 3, value = "jng" },
        { type = "terrain", q = -4, r = 4, value = "jng" },
        { type = "terrain", q = -4, r = 5, value = "jng" },
        { type = "terrain", q = -3, r = 0, value = "jng" },
        { type = "terrain", q = -3, r = 1, value = "rvr" },
        { type = "terrain", q = -3, r = 2, value = "jng" },
        { type = "terrain", q = -3, r = 3, value = "jng" },
        { type = "terrain", q = -2, r = -1, value = "jng" },
        { type = "terrain", q = -2, r = 1, value = "rvr" },
        { type = "terrain", q = -2, r = 2, value = "rvr" },
        { type = "terrain", q = -1, r = -2, value = "jng" },
        { type = "terrain", q = -1, r = -1, value = "jng" },
        { type = "terrain", q = -1, r = 2, value = "rvr" },
        { type = "terrain", q = -1, r = 4, value = "jng" },
        { type = "terrain", q = -1, r = 5, value = "jng" },
        { type = "terrain", q = 0, r = -2, value = "jng" },
        { type = "terrain", q = 0, r = 1, value = "rvr" },
        { type = "terrain", q = 0, r = 3, value = "jng" },
        { type = "terrain", q = 1, r = -2, value = "jng" },
        { type = "terrain", q = 1, r = 0, value = "jng" },
        { type = "terrain", q = 1, r = 1, value = "rvr" },
        { type = "terrain", q = 2, r = -1, value = "jng" },
        { type = "terrain", q = 2, r = 0, value = "jng" },
        { type = "terrain", q = 2, r = 1, value = "rvr" },
        { type = "terrain", q = 2, r = 2, value = "rvr" },
        { type = "site", q = -1, r = 1, value = "val" },
    },
}
