return {
    version = 1,
    name = "map001",
    tiles = {
        { layer = "base", q = -4, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -4, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -4, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -3, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -2, r = 4, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = -2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = -1, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = -2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 0, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 2, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 1, r = 3, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 2, r = -1, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "base", q = 2, r = 0, folder = "green", name = "PH2_FjordSummerGrass_3.png", path = "assets/images/maptiles/hex_bases/green/PH2_FjordSummerGrass_3.png" },
        { layer = "road", q = -1, r = 3, folder = "road_dark", name = "PH2_RoadDark_19.png", path = "assets/images/maptiles/river_road_bridge/road_dark/PH2_RoadDark_19.png" },
        { layer = "road", q = 0, r = 0, folder = "road_dark", name = "PH2_RoadDark_19.png", path = "assets/images/maptiles/river_road_bridge/road_dark/PH2_RoadDark_19.png" },
        { layer = "road", q = 0, r = 1, folder = "road_dark", name = "PH2_RoadDark_17.png", path = "assets/images/maptiles/river_road_bridge/road_dark/PH2_RoadDark_17.png" },
        { layer = "road", q = 0, r = 2, folder = "road_dark", name = "PH2_RoadDark_07.png", path = "assets/images/maptiles/river_road_bridge/road_dark/PH2_RoadDark_07.png" },
        { layer = "road", q = 1, r = -1, folder = "road_dark", name = "PH2_RoadDark_26.png", path = "assets/images/maptiles/river_road_bridge/road_dark/PH2_RoadDark_26.png" },
        { layer = "river", q = -3, r = 1, folder = "rivers", name = "PH2_RiverNordic_22.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_22.png" },
        { layer = "river", q = -2, r = 1, folder = "rivers", name = "PH2_RiverNordic_00.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_00.png" },
        { layer = "river", q = -2, r = 2, folder = "rivers", name = "PH2_RiverNordic_35.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_35.png" },
        { layer = "river", q = -1, r = 2, folder = "rivers", name = "PH2_RiverNordic_23.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_23.png" },
        { layer = "river", q = 0, r = 2, folder = "rivers", name = "PH2_RiverNordic_32.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_32.png" },
        { layer = "river", q = 1, r = 1, folder = "rivers", name = "PH2_RiverNordic_10.png", path = "assets/images/maptiles/river_road_bridge/rivers/PH2_RiverNordic_10.png" },
        { layer = "bridge", q = 0, r = 2, folder = "bridges", name = "PH2_Bridges_01.png", path = "assets/images/maptiles/river_road_bridge/bridges/PH2_Bridges_01.png" },
        { layer = "overlay", q = -3, r = 1, folder = "woods", name = "PH2_ThickForest_16.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_16.png" },
        { layer = "overlay", q = -3, r = 2, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -3, r = 3, folder = "woods", name = "PH2_ThickForest_05.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_05.png" },
        { layer = "overlay", q = -2, r = 0, folder = "woods", name = "PH2_ThickForest_00.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_00.png" },
        { layer = "overlay", q = -2, r = 1, folder = "woods", name = "PH2_ThickForest_16.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_16.png" },
        { layer = "overlay", q = -2, r = 3, folder = "woods", name = "PH2_ThickForest_05.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_05.png" },
        { layer = "overlay", q = 0, r = -1, folder = "woods", name = "PH2_ThickForest_05.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_05.png" },
        { layer = "overlay", q = 1, r = 0, folder = "woods", name = "PH2_ThickForest_05.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_05.png" },
        { layer = "overlay", q = 1, r = 1, folder = "woods", name = "PH2_ThickForest_21.png", path = "assets/images/maptiles/hex_overlays/woods/PH2_ThickForest_21.png" },
    },
    markers = {
        { type = "site", q = -1, r = 1, value = "play_start" },
    },
}
